# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-21 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_title', models.CharField(max_length=20, verbose_name='标题')),
                ('img', models.ImageField(upload_to='', verbose_name='信息')),
                ('img_pub_date', models.DateField(verbose_name='发布日期')),
                ('img_read', models.IntegerField(default=0, verbose_name='阅读量')),
                ('img_good_star', models.IntegerField(default=0, verbose_name='好评量')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': 'tb_images',
            },
        ),
        migrations.CreateModel(
            name='ImageSearchContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=100, verbose_name='字段')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('txt_img_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_app.ImageInfo', verbose_name='所属图片')),
            ],
            options={
                'verbose_name': '图片搜索字段',
                'verbose_name_plural': '图片搜索字段',
                'db_table': 'tb_images_search_context',
            },
        ),
    ]
