# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-21 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='img',
            field=models.ImageField(upload_to='media', verbose_name='信息'),
        ),
    ]
