# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-23 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0002_auto_20190521_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='img_pub_date',
            field=models.DateField(auto_now=True, verbose_name='发布日期'),
        ),
    ]
